ai_img_classification/ai_img_classification/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin

from django.contrib.auth.decorators import login_required


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/',include('applications.accounts.urls')),
    url(r'^', include('applications.media_handler.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ai_img_classification/applications/accounts/models.py
import os
from django.conf import settings
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.utils.translation import ugettext as _
from django.dispatch import receiver

class TimeStampModel(models.Model):
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

class User(AbstractUser, TimeStampModel):
    Uid = models.CharField(max_length=20,null=True,blank=True)
    profile_image = models.FileField(upload_to='profile_images',null=True,blank=True)

    def __str__(self):
        return self.username


class Logs(TimeStampModel):
    in_time = models.TimeField(auto_now=False, auto_now_add=False,null=True,blank=True)
    out_time = models.TimeField(auto_now=False, auto_now_add=False,null=True,blank=True)
    date = models.DateTimeField(null=True,auto_now_add=False,auto_now=False,blank=True)
    total_hours = models.CharField(max_length=256,null=True,blank=True)
    user_obj = models.ForeignKey(User,related_name="uid",on_delete=models.CASCADE,null=True,blank=True)

    def __str__(self):
        return self.user_obj.first_name + " " + str(self.date)

def content_file_name(instance, filename):
    ext = filename.split('.')[-1]
    filename = instance.user_obj.first_name + "_" + "." + ext
    print(filename,"aaa")
    return os.path.join("training/%d-%m-%Y", filename)

class UserImages(TimeStampModel):
    user_obj = models.ForeignKey(User,related_name="user_image",on_delete=models.CASCADE,null=True,blank=True)
    image = models.FileField(upload_to="training/%Y/%m/%d", null=True,blank=True)

    def __str__(self):
        return self.user_obj.first_name

    class Meta:
        verbose_name_plural = "UserImages"


def user_directory_path(instance, filename):
    return instance.user.first_name + "/zips/"


class Attachment(models.Model):
    attachment = models.FileField(upload_to=user_directory_path,null=True,blank=True)
    export_dir = models.FileField(upload_to="exports",null=True,blank=True)
    user = models.ForeignKey(User,related_name="user_obj",on_delete=models.CASCADE,null=True)
    extracts = models.FileField(upload_to="extracts",null=True,blank=True)

@receiver(models.signals.post_delete, sender=Attachment)
def auto_delete_file_on_delete(sender, instance, **kwargs):
    """
    Deletes file from filesystem
    when corresponding `MediaFile` object is deleted.
    """
    if instance.attachment:
        if os.path.isfile(instance.attachment.path):
            os.remove(instance.attachment.path)
            # d = "media/"+ instance.user.first_name + "/extracts/"+ instance.attachment.name
            # shutil.rmtree(d)




@receiver(models.signals.post_delete, sender=UserImages)
def auto_delete_file_on_delete(sender, instance, **kwargs):
    """
    Deletes file from filesystem
    when corresponding `MediaFile` object is deleted.
    """
    if instance.image:
        if os.path.isfile(instance.image.path):
            os.remove(instance.image.path)

# @receiver(models.signals.post_save, sender=UserImages)
# def auto_rename(sender, instance, **kwargs):
#     """
#     Deletes file from filesystem
#     when corresponding `MediaFile` object is deleted.
#     """
#     if instance.image:
#         ext = instance.image.name.split('.')[-1]
#         instance.image.name = instance.user_obj.first_name + "_" + "." + ext
#         instance.save()

class TrainingFile(TimeStampModel):
    dat_file = models.FileField(db_index=True, upload_to='models')

    def __str__(self):
        return self.dat_file.name

ai_img_classification/templates/base.html
{% load static %}
<html lang="en">
<head>
    <!-- b-win-cd-02 -->
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta http-equiv="content-type" content="text/html;charset=utf-8"/>

    <!--Page Metadata-->
    <title>UST GLOBAL</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1,user-scalable=no">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="HandheldFriendly" content="true">

    <meta http-equiv="cache-control" content="no-store">
    <meta http-equiv="expires" content="0">
    <meta http-equiv="pragma" content="no-cache">
    <meta name="robots" content="follow, index"/>
    <meta name="language" content="en"/>
    <meta name="description"
          content="Perissos Private Wealth Management’s investing principles are grounded in the idea of causality; breaking down complex economic environments into their simple moving parts to identify cause-effect relationships to guide our decision making process"/>
    <link rel="canonical" href="index.html">
    <!-- Open Graph data -->
    <meta property="og:title" content="Perissos Private Wealth Management"/>
    <meta property="og:description"
          content="Perissos Private Wealth Management’s investing principles are grounded in the idea of causality; breaking down complex economic environments into their simple moving parts to identify cause-effect relationships to guide our decision making process"/>
    <meta property="og:type" content="website"/>
    <meta property="og:url" content="index.html"/>
    <meta property="og:locale" content="en_US"/>
    <meta property="og:site_name" content="Perissos Private Wealth Management"/>
    <meta name="twitter:card" content="summary"/>
    <link rel="stylesheet" type="text/css" href="https://perissos-production.s3.amazonaws.com/assets/fonts/font-awesome-4.7.0/css/font-awesome.min.css">
<!--    <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>-->
        <script type="text/javascript" src="{% static 'js/jquery-3.3.1.min.js' %}"></script>

<!--    <link rel='stylesheet' href="https://perissos-production.s3.amazonaws.com/assets/css/global.min7f2f.css"/>-->
    <link rel='stylesheet' href="{% static 'css/global.css' %}"/>
    <link rel='stylesheet' href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.17.37/css/bootstrap-datetimepicker.css"/>
<!--    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" rel="stylesheet">-->

    <link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/js/bootstrap.min.js"></script>

    <link rel="stylesheet" href="{% static 'css/footer.css' %}">
    <link rel="stylesheet" href="{% static 'css/account.css' %}">
      <link rel="stylesheet" href="http://code.jquery.com/ui/1.10.3/themes/smoothness/jquery-ui.css">

    <!--<link rel='stylesheet' href="https://perissos-production.s3.amazonaws.com/assets/css/home.css"/>-->
<!--    <link href="https://perissos-production.s3.amazonaws.com/assets/images/favicon.ico" rel="shortcut icon" type="image/x-icon" />-->
<!--    <link rel="apple-touch-icon" sizes="57x57" href="https://perissos-production.s3.amazonaws.com/assets/images/favicon/apple-icon-57x57.png">-->
<!--    <link rel="apple-touch-icon" sizes="60x60" href="https://perissos-production.s3.amazonaws.com/assets/images/favicon/apple-icon-60x60.png">-->
<!--    <link rel="apple-touch-icon" sizes="72x72" href="https://perissos-production.s3.amazonaws.com/assets/images/favicon/apple-icon-72x72.png">-->
<!--    <link rel="apple-touch-icon" sizes="76x76" href="https://perissos-production.s3.amazonaws.com/assets/images/favicon/apple-icon-76x76.png">-->
<!--    <link rel="apple-touch-icon" sizes="114x114" href="https://perissos-production.s3.amazonaws.com/assets/images/favicon/apple-icon-114x114.png">-->
<!--    <link rel="apple-touch-icon" sizes="120x120" href="https://perissos-production.s3.amazonaws.com/assets/images/favicon/apple-icon-120x120.png">-->
<!--    <link rel="apple-touch-icon" sizes="144x144" href="https://perissos-production.s3.amazonaws.com/assets/images/favicon/apple-icon-144x144.png">-->
<!--    <link rel="apple-touch-icon" sizes="152x152" href="https://perissos-production.s3.amazonaws.com/assets/images/favicon/apple-icon-152x152.png">-->
<!--    <link rel="apple-touch-icon" sizes="180x180" href="https://perissos-production.s3.amazonaws.com/assets/images/favicon/apple-icon-180x180.png">-->
<!--    <link rel="icon" type="image/png" sizes="192x192" href="https://perissos-production.s3.amazonaws.com/assets/images/favicon/android-icon-192x192.png">-->
<!--    <link rel="icon" type="image/png" sizes="32x32" href="https://perissos-production.s3.amazonaws.com/assets/images/favicon/favicon-32x32.png">-->
<!--    <link rel="icon" type="image/png" sizes="96x96" href="https://perissos-production.s3.amazonaws.com/assets/images/favicon/favicon-96x96.png">-->
<!--    <link rel="icon" type="image/png" sizes="16x16" href="https://perissos-production.s3.amazonaws.com/assets/images/favicon/favicon-16x16.png">-->
<!--    <link rel="manifest" href="https://perissos-production.s3.amazonaws.com/assets/images/favicon/manifest.json">-->
<!--    <meta name="msapplication-TileColor" content="#ffffff">-->
    <meta name="msapplication-TileImage" content="https://perissos-production.s3.amazonaws.com/assets/images/favicon/ms-icon-144x144.png">
    <meta name="theme-color" content="#ffffff">
</head>
<nav class="global-header trackable" id="global-header" data-component-name="Header" data-content-name="Global Header">
    <div class="container">
        <a id="nav-mobile-menu" class="nav-mobile-menu">
            <img src="https://perissos-production.s3.amazonaws.com/assets/images/menu.png" alt="open menu" class="hamburger-menu"/>
            <img src="https://perissos-production.s3.amazonaws.com/assets/images/close-white.png" alt="close menu" class="close-menu"/>
        </a>

        <!-- <a href="index.html" class="logo" data-target-title="Dimensional Investing | Dimensional Fund Advisors" ><img src="-/media/Dimensional/Images/Global/logob1c1.svg?la=en&amp;hash=C102AF43E54D411D52078223936CD9CD2ECC3117" alt="Dimensional Logo" /></a> -->
        <a href="/" class="logo" data-target-title="Perissos Private Wealth Management">
            <img width="200px" class="" height="60px" src="{% static 'images/logo.png' %}" alt="Ust Logo"/></a>

        <div class="nav-links">
            <ul class="nav-links-main">

<!--                <li class="list ">-->
<!--                    <a href="/individual-investor/" class="">Individual Investor</a>-->
<!--                </li>-->
                {% if not "login" in request.path %}
                {% if not request.user.is_authenticated  %}
                <li class="list ">
                    <a href="{% url 'login' %}" class="">Login</a>
                </li>
                {% else %}
                <li class="list">
                <a href="/" class="">Home</a>
                </li>

                <button class="button logout"><a href="{% url 'logout' %}" class="">Logout</a></button>
                {% endif %}
                {% endif %}

            </ul>
        </div>
    </div>
</nav>
<body id="load" class="body-class bg-color">
{% block content %}
{% endblock %}
<!--<script type='text/javascript' src="https://perissos-production.s3.amazonaws.com/assets/js/plugins/fingerprint.js"></script>-->
<script type='text/javascript' src="https://perissos-production.s3.amazonaws.com/assets/js/global/dimensional.main3c5d.js"></script>
<!--<script type='text/javascript' src="https://perissos-production.s3.amazonaws.com/assets/js/component/dim_detail.min3c5d.js"></script>-->
<!--<script type='text/javascript' src="https://perissos-production.s3.amazonaws.com/assets/js/component/auxiliary.min3c5d.js"></script>-->
<!--<script type='text/javascript' src="https://perissos-production.s3.amazonaws.com/assets/js/global/splash.min3c5d.js"></script>-->
<script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.15.1/moment.min.js"></script>
<script type='text/javascript' src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/3.1.3/js/bootstrap-datetimepicker.min.js"></script>
<!--<script type='text/javascript' src="https://perissos-production.s3.amazonaws.com/assets/js/component/fund-center.min7b31.js"></script>-->
<script src="http://code.jquery.com/ui/1.10.3/jquery-ui.js"></script>
<script>

</script>
</body>
<!--     <div id ="footer">-->
<!--        <div id="footer-main">-->
<!--            <div id="footer-links">-->
<!--                <ul id="footer-links-main">-->
<!--                    <li>-->
<!--                    <a href="/company/disclosure/" >Disclosure</a>-->
<!--                    </li>-->
<!--                    <li>-->
<!--                    <a href="/company/privacy-policy/">Privacy Policy</a>-->
<!--                    </li>-->
<!--                </ul>-->
<!--            </div>-->
<!--        </div>-->

<!--        <div id="footer-links-legal">-->
<!--            <ul>-->
<!--                <li id="footer-legal-copyright">-->
<!--                Ust Global-->
<!--                </li>-->
<!--            </ul>-->
<!--        </div>-->
<!--     </div>-->


</html>

ai_img_classification/templates/capture.html
{% extends 'base.html' %}
{% block content %}


<div class="container-large ofh pos-rel bg-white no-padding bg-color">
    <div class="trackable" data-component-name="Audience Hero" data-content-name="TDIF Hero">
        <div class="container m-top ">
                <div class="row center">
                    <div class="col-md-6 col-sm-12 webcam ">
                        <div class="webcam-container">
                            <video id="video" class="webcam-container" autoplay="true"></video>
                        </div>
                        <p>
                        <div>
                            <span id="camera" onclick="toggleFunction();"><i class="fa fa-play pointer"
                                                                          aria-hidden="true"></i></span>
                            <span onclick="snapshot();"><i class="fa fa-camera pointer" aria-hidden="true"></i></span>
                        </div>
                        </p>
                    </div>
                    <form id="img-upload-form" enctype="multipart/form-data" class="{% if request.GET.multiple %} hidden {% endif %}">
                        {% csrf_token %}
                    <div class="col-md-4 col-sm-12">
                        <canvas id="myCanvas" class="hidden" width="250" height="250"></canvas>
                        <p>Screenshots :</p>
                        <div id="image" class="image-container1 hidden">
                            <div class="col-md-12 col-sm-12" id="class1">

                            </div>
                        </div>
<!--                        modal-->
                        <!-- The Modal -->
                        <div id="myModal" class="modal">
                          <span class="close">&times;</span>
                            <span class="trash"><i class="fa fa-trash"  onclick="deleteImg(this.id);"></i></span>
                          <img class="modal-content" id="img01">
                          <div id="caption"></div>
                        </div>
                        <div class="form-inline top-margin">
                            <div class="form-group">
                                <label for="name" class="col-sm-2 pt-top">Name*</label>
                                <input type="text" id="name" name="name" class="form-control">
                            </div>
                        </div>
                        <div class="form-inline top-margin">
                            <div class="form-group">
                                <label for="uid" class="col-sm-2 pt-top">Uid*</label>
                                <input type="text" id="uid" name="uid" class="form-control">
                            </div>
                        </div>
                        <div id="error" class="hidden"></div>
<!--                        <div id="success" style="color:green;"></div>-->
                        <div class="form-group {% if request.GET.multiple %}buttons{% endif %}">
                            <button class="button large expanded" id="submit" type="submit">Submit</button>
                        </div>
                    </div>
                    </form>

                    {% if request.GET.multiple %}
                <button id="train" class="button large expanded" type="button">Train</button>
                <button id="add_user" class="button large expanded" type="button">Add Another User</button>
                                        <div id="success" style="color:green;"></div>

                {% endif %}

                </div>
                        </div>
    </div>
</div>
<script>
var modal = document.getElementById("myModal");
var src = '';
function popup(id,url){
// Get the image and insert it inside the modal - use its "alt" text as a caption
var img = document.getElementById(id);
var modalImg = document.getElementById("img01");
  modal.style.display = "block";
  modalImg.src = url;
  src = url;
  value = url.slice(70,85);
  $('.fa-trash').attr('id', value);
}

// Get the <span> element that closes the modal
var span = document.getElementsByClassName("close")[0];

// When the user clicks on <span> (x), close the modal
span.onclick = function() {
  modal.style.display = "none";
}

function deleteImg(string)
{
console.log(string);
<!--$('.fa-trash').attr('id', "changed");-->
<!--element1 = $("#"+string).remove();-->
$("."+string).remove();
$(".close").click();
}


$("#add_user").click(function(){
if($("#img-upload-form").hasClass("hidden")){
    $("#img-upload-form").removeClass("hidden");
        $('#train').prop("disabled", true);

    $("#add_user").text("Add Later");
    }
    else{

        $("#img-upload-form").addClass("hidden");
        $('#train').prop("disabled", false);

        $("#add_user").text("Add Another User");
            $("#train").removeAttr("disabled");
    }
});

       var toggle = true;

    function toggleFunction(){
        toggle ? startWebcam() : stopWebcam();
        toggle = !toggle;
}

      //--------------------
      // GET USER MEDIA CODE
      //--------------------
          navigator.getUserMedia = ( navigator.getUserMedia ||
                             navigator.webkitGetUserMedia ||
                             navigator.mozGetUserMedia ||
                             navigator.msGetUserMedia);

      var video;
      var webcamStream;

      function startWebcam() {
        document.querySelector('#camera').innerHTML  = '<i class="fa fa-stop" aria-hidden="true"></i>';
        if (navigator.getUserMedia) {
           navigator.getUserMedia (

              // constraints
              {
                 video: true,
                 audio: false
              },

              // successCallback
              function(localMediaStream) {
                  video = document.querySelector('video');
                 video.srcObject=localMediaStream;
                 webcamStream = localMediaStream;
              },

              // errorCallback
              function(err) {
                 console.log("The following error occured: " + err);
              }
           );
        } else {
           console.log("getUserMedia not supported");
        }
      }

      function stopWebcam() {
        webcamStream.getTracks()[0].stop();
        document.querySelector('#camera').innerHTML  = '<i class="fa fa-play" aria-hidden="true"></i>';

        }
      //---------------------
      // TAKE A SNAPSHOT CODE
      //---------------------
      var canvas, ctx;

      function init() {
        // Get the canvas and obtain a context for
        // drawing in it
        canvas = document.getElementById("myCanvas");
        ctx = canvas.getContext('2d');
      }

      function snapshot() {
         // Draws current image from the video element into the canvas
        canvas = document.getElementById("myCanvas");
        ctx = canvas.getContext('2d');
        video = document.querySelector('video');
        ctx.drawImage(video, 0,0, canvas.width, canvas.height);
        var image = new Image();
        var data = canvas.toDataURL("image/png");
        image.src = data;
        sliced = data.slice(70,85);
        $('<input>').attr({
        type: 'hidden',
        id: 'foo',
        class:sliced,
        name: 'filename[]',
        value:data
        }).appendTo('form');
        $("#image").removeClass("hidden");
        $("#class1").append("<img class='" + sliced + "' onclick=popup(this.id,this.src) class='zoom' height='50px' width='50px' src='"+ data + "'></img> ")

      }

$("#train").click(function(){
    var xhttp = new XMLHttpRequest();
    $('#success').html("Training Initiated...");
    $("#train").attr("disabled", true);
    $("#submit").attr("disabled", true);

<!--    $('.container').fadeOut(2000);-->

    xhttp.onreadystatechange = function() {
        if (this.readyState == 4 && this.status == 200) {
           // Typical action to be performed when the document is ready:
           console.log(xhttp.responseText);
           var response =xhttp.responseText;
           var jsonResponse = JSON.parse(response);
                $('#success').html(jsonResponse["success"]);
                setTimeout(function() {
                        $('#success').html('');
                        }, 5000);
<!--           $('.container').fadeIn(2000);-->
                 $("#train").attr("disabled", false);
                $("#submit").attr("disabled", false);

        }
    };

xhttp.open("GET", "{% url 'training' %}", true);
xhttp.send();
});


$("#img-upload-form").submit(function(e) {
    e.preventDefault();
    var formData = new FormData(this);
    $.ajax({
    url : "{% url 'capture-images' %}",
    crossDomain: true,
    type : "POST",
    data : formData,
    dataType:'json',
    contentType: false,
    processData: false,
        success : function(data) {
        console.log(data);
            if (data.result != "success")
             {
                response = data.result;
                $('#error').removeClass('hidden');
                $('#error').html(response);
             }
             else{
                 window.location.href = "{% url 'capture-images' %}"+"?multiple=true" ;
                }
         },
        // handle a non-successful response
        error : function(xhr,errmsg,errors) {
        console.log(xhr.status + ": " + xhr.responseText);
        console.log(errors)// provide a bit more info about the error to the console
        }
    });

});







</script>
{% endblock %}

ai_img_classification/templates/user-log-detail.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="container-large ofh pos-rel bg-white no-padding bg-color">
    <div class="container m-top">
        <div class="row">
            <div class="col-md-8">
                <h1>{{user.first_name}}'s Attendence History</h1><h4>User added on :{{created}}</h4>
                <a href data-toggle="modal" data-target="#images">view user-images</a>
            </div>
            <!--                <div class="col-md-4">-->
            <!--                    <form id="date_form">-->
            <!--                        <div class="form-group">-->
            <!--                            <input type='date' value="{{today | date:'Y-m-d' }}"-->
            <!--                                   class="form-control hidden" name="date" id="id_date"-->
            <!--                                   value="{% if request.GET.date %}{{request.GET.date}}{% endif %}"/>-->
            <!--                        </div>-->
            <!--                    </form>-->
            <!--                </div>-->
            <!--                <div class="col-md-4">-->
            <!--                    <i class="fa fa-calendar pointer add-user" aria-hidden="true"></i>-->
            <!--                    <form id="date_form">-->
            <!--                    <input type="date" name="date" id="datepicker" class="hidden" value="{{today | date:'Y-m-d' }}"-->
            <!--                    value="{% if request.GET.date %}{{request.GET.date}}{% endif %}">-->
            <!--                    </form>-->
            <!--                </div>-->

        </div>
        <table class="responstable">
            <tr>
                <th>Date</th>
                <th data-th="Driver details"><span>Attendence Status</span></th>
                <th>In-Time</th>
                <th>Out-Time</th>
                <th>Total Hours</th>
            </tr>
            {% for log in page_obj %}
            <tr>
                <td>{{ log.date }}</td>
                <td>{{log.status}}</td>
                <td>{{ log.in_time }}</td>
                <td>{{ log.out_time }}</td>
                <td>{{ log.total_hour }}</td>
            </tr>
            {% empty %}
            {% for log in
            <tr>
                <td colspan="7">
                    There are no entries yet
                </td>
            </tr>
            {% endfor %}
            <!--                <tr>-->
            <!--                    <td>Steffie</td>-->
            <!--                    <td>Steffie</td>-->
            <!--                    <td>Foo</td>-->
            <!--                    <td>Foo</td>-->
            <!--                    <td>01/01/1978</td>-->
            <!--                    <td>Spouse</td>-->
            <!--                </tr>-->

            <!--                <tr>-->
            <!--                    <td>Stan</td>-->
            <!--                    <td>Stan</td>-->
            <!--                    <td>Stan</td>-->
            <!--                    <td>Foo</td>-->
            <!--                    <td>01/01/1994</td>-->
            <!--                    <td>Son</td>-->
            <!--                </tr>-->

            <!--                <tr>-->
            <!--                    <td>Stella</td>-->
            <!--                    <td>Stella</td>-->
            <!--                    <td>Foo</td>-->
            <!--                    <td>Foo</td>-->
            <!--                    <td>01/01/1992</td>-->
            <!--                    <td>Daughter</td>-->
            <!--                </tr>-->


        </table>
        {% if page_obj.has_previous %}
        <a href="?page=1">&laquo; first</a>
        <a href="?page={{ page_obj.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
        </span>

        {% if page_obj.has_next %}
        <a href="?page={{ page_obj.next_page_number }}">next</a>
        <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
        {% endif %}
    </div>
</div>
<!--begin modal window-->
<div class="modal fade" id="images">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header header">
                <div class="pull-left">User Images</div>
                <button type="button" class="close" data-dismiss="modal" title="Close"><span class="glyphicon glyphicon-remove"></span></button>
            </div>
            <div class="modal-body">
                <div id="myGallery" class="carousel slide" data-interval="false">
                    <div class="carousel-inner user-gallery">
                        {% for image in images %}
                        <div class="item {% if forloop.counter == 1 %} active{% endif %}"><img src="{{image.image.url}}" alt="item0">
                            <div class="carousel-caption">
                            </div>
                        </div>
                        {% endfor %}
                    </div>
                    <a class="left carousel-control" href="#myGallery" role="button" data-slide="prev"> <span class="glyphicon glyphicon-chevron-left"></span></a> <a class="right carousel-control" href="#myGallery" role="button" data-slide="next"> <span
                        class="glyphicon glyphicon-chevron-right"></span></a>
                    </div>
            </div>
            <div class="modal-footer">
            </div>
            </div>
        </div>
</div>
<script>
    $('td').each(function() {
     var className = $(this).html().replace(' ', '').toLowerCase();
     $(this).addClass(className);
});

</script>
{% endblock %}

ai_img_classification/templates/user_logs.html
{% extends 'base.html' %}
{% load static %}


{% block content %}
 <meta http-equiv="refresh" content="10">

<div class="container-large ofh pos-rel bg-white no-padding bg-color margin-top">
    <div class="container">
        <div class="col-sm-6 col-md-2" style="height:130px;">
            <form id="date_form">
                <div class="form-group">
                    <!--                                <div class='input-group date' id='datetimepicker10'>-->
                    <input type='date' value="{{today | date:'Y-m-d' }}"
                           class="form-control" name="date" id="id_date"
                           value="{% if request.GET.date %}{{request.GET.date}}{% endif %}"/>
                    <!--                                    <span class="input-group-addon">-->
                    <!--                                        <span class="glyphicon glyphicon-calendar">-->
                    <!--                                        </span>-->
                    <!--                                    </span>-->
                    <!--                                </div>-->
                </div>
            </form>
        </div>
        <script type="text/javascript">
                            $(function () {
                                $('#datetimepicker10').datetimepicker({
                                    viewMode: 'dates',
                                    format: 'MM/YYYY/DD'

                                });
                            });


        </script>
    </div>

</div>
        <div class="container emp-profile">
            <form method="post">
                <div class="row">
                    <div class="col-md-6">
                        <div class="profile-head">
                                    <h5>
                                        {{user.first_name }}
                                    </h5>
                                    <h6>
                                        Uid:{{user.Uid}}
                                    </h6>
                        </div>
                    </div>
                </div>
                <div class="row">
                    {% for log in logs %}
                    <div class="col-md-4">
                        <div class="profile-work">
                            <p>Date : {{log.date}}</p>
                            <a href="">in-time: {{log.in_time}}</a><br/>
                            <a href="">out-time:{{log.out_time}}</a><br/>
                            <a href="">total-hours:{{log.total_hours}}</a>
                        </div>
                    </div>
                    {% endfor %}
                </div>
            </form>
        </div>


<script>

$("#id_date").change(function(){
$("#date_form").submit();
});
</script>


{% endblock %}